[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
detekt = "1.23.8"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
mockk = "1.14.9"
mockk-android = "1.14.9"
shot = "6.1.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
constraintlayoutCompose = "1.1.1"
kotlin = "2.3.0"
google-ksp = "2.3.2"
google-services = "4.4.4"
composeBom = "2026.01.01"
composeMaterialIcons = "1.7.8"
retrofit = "3.0.0"
kotlinSerialization = "2.3.0"
kotlinxSerializationCore = "1.10.0"
fancyComposeAlertDialog = "1.0.2"
okhttp = "5.3.2"
coroutines = "1.10.2"
navigation3 = "1.0.0"
lifecycleViewmodelNavigation3 = "2.10.0"
materialAdaptiveNavigation3 = "1.2.0"
compose-shimmer = "1.3.3"
koin = "4.1.1"
koin-annotations = "2.3.1"
coil-images = "3.3.0"
firebase-bom = "34.8.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit = { group = "io.insert-koin", name = "koin-test-junit4", version.ref = "koin" }
mockk-io = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk-android" }
shot = { module = "com.karumi:shot", version.ref = "shot" }
shot-android = { group = "com.karumi", name = "shot-android", version.ref = "shot" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "composeMaterialIcons" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIcons" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer"}
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_converter_gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
compose-alert-dialog = { group = "com.github.PratikFagadiya", name = "FancyJetpackComposeDialog", version.ref = "fancyComposeAlertDialog" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-annotation = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotations" }
coil-images = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-images"}
coil-images-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-images"}
coil-test = { group = "io.coil-kt.coil3", name = "coil-test", version.ref = "coil-images"}
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNavigation3" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "materialAdaptiveNavigation3" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth"}

[bundles]
coroutines = ["coroutines", "coroutines-core"]
retrofit = ["retrofit", "retrofit_converter_gson"]
firebase = ["firebase-firestore", "firebase-auth"]
coil-images = ["coil-images", "coil-images-network"]
koin = ["koin", "koin-annotation", "koin-compose"]
koin-test = ["koin-test", "koin-test-junit"]
navigation3 = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-lifecycle-viewmodel-navigation3",
    "kotlinx-serialization-core",
    "androidx-material3-adaptive-navigation3"
]

composeIcons = [
    "androidx-compose-material-icons-core",
    "androidx-compose-material-icons-extended"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
google-gms-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization"}

